name: Call Reusable Build and Push Workflow

on:
  push:
    branches:
      - main  
  workflow_dispatch:  

permissions: 
  contents: read
  packages: write

jobs:
  build-and-push:
    uses: omartinex/buil-push-docker-image-wf/.github/workflows/build-and-push.yml@main  
    with:
      dockerfilePath: './Dockerfile'  
      imageName: 'redis-alpine'       
      imageTag: 'latest'             
